# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:

  vmImage: ubuntu-latest
variables: 
    imageName: 'acruktest01.azurecr.io/flask_test'


steps:
- task: Docker@2
  displayName: 'Building a docker image and pushing it to ACR'
  inputs:
    containerRegistry: 'acrukstest01'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'


